-- Stable control IDs and presentation schema. Session behavior is supplied as callbacks.
local R = {}
local required = {
    'apply_activate',
    'apply_armor_activate',
    'apply_checked_activate',
    'apply_editor_activate',
    'apply_file_armor_activate',
    'apply_file_both_activate',
    'apply_file_helmet_activate',
    'apply_helmet_activate',
    'apply_import_armor_activate',
    'apply_import_helmet_activate',
    'apply_matching_activate',
    'armory_export_activate',
    'armory_export_format_change',
    'armory_import_activate',
    'basic_advanced_activate',
    'basic_armor_lut_change',
    'basic_cape_lut_change',
    'basic_copy_armor_activate',
    'basic_copy_helmet_activate',
    'basic_copy_helmet_all_activate',
    'basic_export_activate',
    'basic_helmet_lut_change',
    'basic_preset_change',
    'basic_save_activate',
    'browse_activate',
    'cancel_import_activate',
    'editor_all_armor_activate',
    'editor_all_both_activate',
    'editor_all_helmet_activate',
    'editor_apply_armor_activate',
    'editor_apply_cape_activate',
    'editor_apply_helmet_activate',
    'editor_load_armor_activate',
    'editor_load_cape_activate',
    'editor_restore_cape_activate',
    'editor_load_helmet_activate',
    'global_redo_activate',
    'global_undo_activate',
    'identify_region_activate',
    'load_activate',
    'load_debug_lut_activate',
    'lut_change',
    'open_editor_activate',
    'outfit_apply_armor_activate',
    'outfit_apply_helmet_activate',
    'outfit_delete_activate',
    'outfit_preset_change',
    'outfit_rename_activate',
    'palette_change',
    'populate_applied_activate',
    'populate_worn_activate',
    'quick_color_change',
    'refresh_activate',
    'remove_lut_activate',
    'reset_custom_activate',
    'restore_activate',
    'restore_imported_activate',
    'retry_import_activate',
    'save_palette_activate',
    'save_setup_activate',
    'stop_identify_activate',
    'ui_scale_change',
}
function R.pages(callbacks, defaults)
    for _, key in ipairs(required) do
        assert(type(callbacks[key]) == 'function', 'Missing editor callback: ' .. key)
    end
    return {
        {
            id = 'direct',
            name = '1. Import / Apply',
            require_confirmation = false,
            controls = {
                {
                    type = 'text',
                    label = 'If Match Your Colors is enabled, turn its color matching Off before applying.',
                },
                {
                    id = 'browse',
                    type = 'button',
                    label = 'Import DDS / ZIP / RAR...',
                    on_activate = callbacks.browse_activate,
                },
                {
                    id = 'load_debug_lut',
                    type = 'button',
                    label = 'Load Debug LUT',
                    description = 'Debug LUT by Plain Furniture. Load a fresh copy into the editor; Apply controls send it to gear.',
                    on_activate = callbacks.load_debug_lut_activate,
                },
                {
                    id = 'cancel_import',
                    type = 'button',
                    label = 'Cancel import',
                    on_activate = callbacks.cancel_import_activate,
                },
                {
                    id = 'retry_import',
                    type = 'button',
                    label = 'Retry file picker',
                    on_activate = callbacks.retry_import_activate,
                },
                { id = 'target_helmet', type = 'toggle', label = 'Apply LUT to Helmet', default = true },
                { id = 'target_armor', type = 'toggle', label = 'Apply LUT to Armor', default = true },
                {
                    id = 'ui_scale',
                    type = 'slider',
                    label = 'UI scale (%)',
                    min = 70,
                    max = 130,
                    step = 5,
                    default = defaults.ui_scale,
                    on_change = callbacks.ui_scale_change,
                },
                {
                    id = 'quick_color',
                    type = 'color',
                    label = 'Quick Scratch',
                    default = '#FFFFFF',
                    on_change = callbacks.quick_color_change,
                },
                { id = 'basic_preset_name', type = 'input', label = 'Preset name', default = 'my-palette' },
                {
                    id = 'apply_matching',
                    type = 'button',
                    label = 'Apply Matching LUTs',
                    on_activate = callbacks.apply_matching_activate,
                },
                {
                    id = 'basic_advanced',
                    type = 'button',
                    label = 'Advanced Mode',
                    on_activate = callbacks.basic_advanced_activate,
                },
                {
                    id = 'open_editor',
                    type = 'button',
                    label = 'Open LUT Editor',
                    on_activate = callbacks.open_editor_activate,
                },
                {
                    id = 'outfit_rename',
                    type = 'button',
                    label = 'Rename Preset',
                    on_activate = callbacks.outfit_rename_activate,
                },
                {
                    id = 'outfit_delete',
                    type = 'button',
                    label = 'Delete Preset',
                    on_activate = callbacks.outfit_delete_activate,
                },
                { id = 'outfit_name', type = 'input', label = 'Preset name', default = 'my-outfit' },
                {
                    id = 'outfit_preset',
                    type = 'choice',
                    label = 'Saved outfit',
                    choices = { 'Choose saved outfit...' },
                    default = 1,
                    on_change = callbacks.outfit_preset_change,
                },
                {
                    id = 'outfit_apply_armor',
                    type = 'button',
                    label = 'Apply Outfit Armor',
                    on_activate = callbacks.outfit_apply_armor_activate,
                },
                {
                    id = 'outfit_apply_helmet',
                    type = 'button',
                    label = 'Apply Outfit Helmet',
                    on_activate = callbacks.outfit_apply_helmet_activate,
                },
                { id = 'armory_export_name', type = 'input', label = 'Armory export name', default = 'my-preset' },
                {
                    id = 'armory_export_format',
                    type = 'choice',
                    label = 'Armory export format',
                    choices = {
                        'Shareable Preset ZIP',
                        'Selected LUT Patch ZIP',
                        'Entire Preset Patch ZIP',
                        'Raw DDS (selected LUT)',
                        'Raw DDS (entire preset)',
                    },
                    default = 1,
                    on_change = callbacks.armory_export_format_change,
                },
                {
                    id = 'armory_dds_naming',
                    type = 'choice',
                    presentation = 'dropdown',
                    label = 'DDS naming',
                    choices = { 'LUT# + HEX', 'LUT# + Decimal', 'LUT#', 'HEX', 'Decimal' },
                    default = 1,
                },
                {
                    id = 'armory_export_lut',
                    type = 'choice',
                    label = 'Saved preset LUT',
                    choices = { 'Choose a saved preset first' },
                    default = 1,
                    disabled = true,
                },
                {
                    id = 'armory_export',
                    type = 'button',
                    label = 'Export Selected Preset...',
                    disabled = true,
                    on_activate = callbacks.armory_export_activate,
                },
                {
                    id = 'armory_import',
                    type = 'button',
                    label = 'Import Shared Preset...',
                    on_activate = callbacks.armory_import_activate,
                },
                {
                    id = 'global_undo',
                    type = 'button',
                    label = 'Undo Last Action',
                    on_activate = callbacks.global_undo_activate,
                },
                {
                    id = 'global_redo',
                    type = 'button',
                    label = 'Redo Last Action',
                    on_activate = callbacks.global_redo_activate,
                },
                {
                    id = 'basic_armor_lut',
                    type = 'choice',
                    presentation = 'dropdown',
                    field_color = { 31, 80, 93 },
                    label = 'Armor LUT #',
                    choices = { 'LUT 1' },
                    default = 1,
                    on_change = callbacks.basic_armor_lut_change,
                },
                {
                    id = 'basic_helmet_lut',
                    type = 'choice',
                    presentation = 'dropdown',
                    field_color = { 31, 80, 93 },
                    label = 'Helmet LUT #',
                    choices = { 'LUT 1' },
                    default = 1,
                    on_change = callbacks.basic_helmet_lut_change,
                },
                {
                    id = 'editor_load_armor',
                    type = 'button',
                    label = 'Populate from Current Armor',
                    on_activate = callbacks.editor_load_armor_activate,
                },
                {
                    id = 'basic_cape_lut',
                    tab_stop = false,
                    type = 'choice',
                    presentation = 'dropdown',
                    field_color = { 31, 80, 93 },
                    label = 'Cape material LUT #',
                    choices = { 'Waiting for gear...' },
                    default = 1,
                    on_change = callbacks.basic_cape_lut_change,
                },
                {
                    id = 'editor_load_cape',
                    tab_stop = false,
                    type = 'button',
                    label = 'Populate from Current Cape',
                    description = 'Edit the cape material colors. Separate cape tint and emblem tables are not edited here.',
                    on_activate = callbacks.editor_load_cape_activate,
                },
                {
                    id = 'editor_apply_cape',
                    tab_stop = false,
                    type = 'button',
                    label = 'Apply to Selected Cape Material LUT',
                    on_activate = callbacks.editor_apply_cape_activate,
                },
                {
                    id = 'editor_restore_cape',
                    tab_stop = false,
                    type = 'button',
                    label = 'Restore Cape Material',
                    on_activate = callbacks.editor_restore_cape_activate,
                },
                {
                    id = 'editor_load_helmet',
                    type = 'button',
                    label = 'Populate from Current Helmet',
                    on_activate = callbacks.editor_load_helmet_activate,
                },
                {
                    id = 'editor_apply_armor',
                    type = 'button',
                    label = 'Apply to Selected Armor LUT',
                    on_activate = callbacks.editor_apply_armor_activate,
                },
                {
                    id = 'editor_apply_helmet',
                    type = 'button',
                    label = 'Apply to Selected Helmet LUT',
                    on_activate = callbacks.editor_apply_helmet_activate,
                },
                {
                    id = 'editor_all_armor',
                    type = 'button',
                    label = 'Apply to All Armor LUTs',
                    on_activate = callbacks.editor_all_armor_activate,
                },
                {
                    id = 'editor_all_both',
                    type = 'button',
                    label = 'Apply to All Armor & Helmet LUTs',
                    on_activate = callbacks.editor_all_both_activate,
                },
                {
                    id = 'editor_all_helmet',
                    type = 'button',
                    label = 'Apply to All Helmet LUTs',
                    on_activate = callbacks.editor_all_helmet_activate,
                },
                {
                    id = 'apply_import_armor',
                    type = 'button',
                    label = 'Apply Imported LUT to Selected Armor LUT',
                    on_activate = callbacks.apply_import_armor_activate,
                },
                {
                    id = 'apply_import_helmet',
                    type = 'button',
                    label = 'Apply Imported LUT to Selected Helmet LUT',
                    on_activate = callbacks.apply_import_helmet_activate,
                },
                {
                    id = 'basic_copy_helmet',
                    type = 'button',
                    label = 'Copy Helmet',
                    on_activate = callbacks.basic_copy_helmet_activate,
                },
                {
                    id = 'basic_copy_helmet_all',
                    type = 'button',
                    label = 'Copy Helmet to All',
                    on_activate = callbacks.basic_copy_helmet_all_activate,
                },
                {
                    id = 'basic_copy_armor',
                    type = 'button',
                    label = 'Copy Armor',
                    on_activate = callbacks.basic_copy_armor_activate,
                },
                {
                    id = 'identify_region',
                    type = 'button',
                    label = 'Identify Region',
                    on_activate = callbacks.identify_region_activate,
                },
                {
                    id = 'stop_identify',
                    type = 'button',
                    label = 'Stop Highlight',
                    on_activate = callbacks.stop_identify_activate,
                },
                {
                    id = 'populate_worn',
                    type = 'button',
                    label = 'Load Current Colors',
                    on_activate = callbacks.populate_worn_activate,
                },
                {
                    id = 'basic_preset',
                    type = 'choice',
                    label = 'Saved palettes',
                    choices = { 'New preset...' },
                    default = 1,
                    on_change = callbacks.basic_preset_change,
                },
                {
                    id = 'basic_save',
                    type = 'button',
                    label = 'Save palette preset',
                    on_activate = callbacks.basic_save_activate,
                },
                {
                    id = 'basic_export',
                    type = 'button',
                    label = 'Export palette DDS',
                    on_activate = callbacks.basic_export_activate,
                },
                { id = 'palette_name', type = 'input', label = 'Palette name', default = 'my-palette' },
                {
                    id = 'populate_applied',
                    type = 'button',
                    label = 'Populate editor with current applied palette',
                    on_activate = callbacks.populate_applied_activate,
                },
                {
                    id = 'save_palette',
                    type = 'button',
                    label = 'Send to LUT Editor',
                    on_activate = callbacks.save_palette_activate,
                },
                {
                    id = 'apply_checked',
                    type = 'button',
                    label = 'Apply to All Checked Targets',
                    on_activate = callbacks.apply_checked_activate,
                },
                {
                    id = 'apply_file_armor',
                    type = 'button',
                    label = 'Apply to Armor',
                    on_activate = callbacks.apply_file_armor_activate,
                },
                {
                    id = 'apply_file_helmet',
                    type = 'button',
                    label = 'Apply to Helmet',
                    on_activate = callbacks.apply_file_helmet_activate,
                },
                {
                    id = 'apply_file_both',
                    type = 'button',
                    label = 'Apply to Both',
                    on_activate = callbacks.apply_file_both_activate,
                },
                {
                    id = 'apply_editor',
                    type = 'button',
                    label = 'Apply edited palette',
                    on_activate = callbacks.apply_editor_activate,
                },
                {
                    id = 'preserve_emissives',
                    type = 'toggle',
                    label = 'Preserve Original Emissives',
                    default = false,
                    description = 'Off by default. Uses matching game-original resource snapshots, preserving zero emissive values. Missing snapshots are not treated as zero.',
                },
                {
                    id = 'palette',
                    type = 'choice',
                    presentation = 'combined',
                    label = 'Imported palette',
                    choices = { 'Import first' },
                    default = 1,
                    on_change = callbacks.palette_change,
                },
                {
                    id = 'refresh',
                    type = 'button',
                    label = 'Refresh live LUTs',
                    on_activate = callbacks.refresh_activate,
                },
                {
                    id = 'lut',
                    type = 'choice',
                    presentation = 'dropdown',
                    label = 'LUT #',
                    choices = { 'Refresh first' },
                    default = 1,
                    on_change = callbacks.lut_change,
                },
                {
                    id = 'scope',
                    type = 'choice',
                    presentation = 'combined',
                    label = 'Apply scope',
                    choices = { 'Selected LUT', 'All Armor LUTs', 'Helmet LUTs', 'All Armor + Helmet LUTs' },
                    default = 4,
                },
                {
                    id = 'apply',
                    type = 'button',
                    label = 'Apply palette',
                    on_activate = callbacks.apply_activate,
                },
                {
                    id = 'apply_armor',
                    type = 'button',
                    label = 'Apply Armor',
                    on_activate = callbacks.apply_armor_activate,
                },
                {
                    id = 'apply_helmet',
                    type = 'button',
                    label = 'Apply Helmet',
                    on_activate = callbacks.apply_helmet_activate,
                },
                {
                    id = 'remove_lut',
                    type = 'button',
                    label = 'Remove LUT',
                    on_activate = callbacks.remove_lut_activate,
                },
                {
                    id = 'save_setup',
                    type = 'button',
                    label = 'Save applied setup',
                    on_activate = callbacks.save_setup_activate,
                },
                {
                    id = 'restore',
                    type = 'button',
                    label = 'Restore Arrowhead LUT (Original)',
                    on_activate = callbacks.restore_activate,
                },
                {
                    id = 'reset_custom',
                    type = 'button',
                    label = 'Reset Custom LUT',
                    on_activate = callbacks.reset_custom_activate,
                },
                {
                    id = 'restore_imported',
                    type = 'button',
                    label = 'Restore Imported LUT',
                    on_activate = callbacks.restore_imported_activate,
                },
                { id = 'status', type = 'text', label = defaults.status },
            },
        },
        {
            id = 'manual',
            name = 'Manual file fallback',
            require_confirmation = false,
            controls = {
                { type = 'text', label = 'Optional fallback: put your file in %LOCALAPPDATA%/Epic LUT/files.' },
                { id = 'format', type = 'choice', label = 'File type', choices = { 'DDS', 'ZIP', 'RAR' }, default = 1 },
                { id = 'file', type = 'input', label = 'Filename (without extension)', default = 'palette' },
                {
                    id = 'load',
                    type = 'button',
                    label = 'Import local file',
                    on_activate = callbacks.load_activate,
                },
            },
        },
    }
end
return R
