"""Maintained Lua bundle inventory. Upstream vendor sources remain unchanged."""
VENDOR = ['bingus_runtime', 'bingus_memory', 'engine', 'avatar', 'lobby_sync', 'armory_watch']
MENU = ['core', 'store', 'menu', 'view', 'capture']
OWN = ['appearance_state', 'text_editor', 'clipboard', 'bulk_dds_export', 'scratch_tool', 'sdk_catalog', 'file_io', 'lut_files', 'patch_export', 'dds', 'palette', 'semantics', 'windows', 'paths', 'preferences', 'frontend', 'lut_editor_controls', 'editor_tools', 'lut_editor_view', 'lut_editor', 'direct_setup', 'import_view', 'table_groups', 'original_luts', 'basic_view', 'armory_view', 'outfit_presets', 'basic_state', 'resource_ids', 'import_matches', 'import_protocol', 'import_job', 'table_index', 'binding_session', 'gear_catalog', 'configuration', 'configuration_view', 'mcm_settings', 'preset_export', 'editor_registry', 'armory_collection', 'control_help', 'region_indicator', 'action_history', 'update_check', 'shared_lut_codec', 'shared_appearance', 'pattern_luts', 'armory_mirror']
PREVIEW = ['player_authored_clip', 'player_authored_source', 'player_animation', 'player_preview_ui', 'limb_caps', 'player_model', 'player_preview', 'player_preview_native', 'player_preview_submit', 'player_preview_controls', 'player_preview_input']

# StyLua 2.5.2 AST verification warns on FFI declarations and embedded worker literals.
# update_check.lua and the LuaJIT lobby fixture trigger verifier panics; preserve their source.
FORMAT_EXCEPTIONS = {'src/gear/sdk_catalog.lua', 'src/platform/windows.lua', 'src/platform/standalone_frontend.lua', 'tests/native_ipc.lua', 'src/gear/shared_lut_codec.lua', 'src/platform/update_check.lua', 'tests/lobby_sync.lua'}

SOURCE_GROUPS = {'player_authored_clip':'preview', 'player_authored_source':'preview', 'player_animation':'preview', 'appearance_state':'gear', 'text_editor':'platform', 'clipboard':'platform', 'bulk_dds_export':'presets', 'scratch_tool':'editor', 'player_preview_ui':'preview', 'sdk_catalog':'gear', 'configuration_view': 'editor','mcm_settings':'platform','preset_export':'presets','editor_tools': 'editor', 'limb_caps': 'preview', 'patch_export': 'presets', 'armory_mirror': 'gear', 'pattern_luts': 'editor', 'shared_lut_codec': 'gear', 'shared_appearance': 'gear', 'action_history': 'core', 'basic_state': 'core', 'dds': 'core', 'file_io': 'core', 'palette': 'core', 'resource_ids': 'core', 'semantics': 'core', 'table_groups': 'core', 'armory_view': 'editor', 'basic_view': 'editor', 'configuration': 'editor', 'control_help': 'editor', 'direct_editor': 'editor', 'editor_registry': 'editor', 'import_view': 'editor', 'lut_editor': 'editor', 'lut_editor_controls': 'editor', 'lut_editor_view': 'editor', 'binding_session': 'gear', 'direct_setup': 'gear', 'gear_catalog': 'gear', 'original_luts': 'gear', 'region_indicator': 'gear', 'import_job': 'imports', 'import_matches': 'imports', 'import_protocol': 'imports', 'table_index': 'imports', 'armory_collection': 'presets', 'lut_files': 'presets', 'outfit_presets': 'presets', 'paths': 'platform', 'preferences': 'platform', 'standalone_frontend': 'platform', 'update_check': 'platform', 'windows': 'platform', 'player_model': 'preview', 'player_preview': 'preview', 'player_preview_candidate': 'preview', 'player_preview_controls': 'preview', 'player_preview_input': 'preview', 'player_preview_native': 'preview', 'player_preview_submit': 'preview', 'startup_bridge': 'loaders', 'startup_bsl': 'loaders', 'bindings': 'legacy', 'catalog': 'legacy', 'document': 'legacy', 'editor': 'legacy', 'editor_features': 'legacy', 'frontend': 'legacy', 'native_import': 'legacy', 'open_companion': 'legacy', 'presets': 'legacy', 'provider_menu': 'legacy', 'session': 'legacy'}

def source_path(name):
    actual = 'standalone_frontend' if name == 'frontend' else name
    return f'src/{SOURCE_GROUPS[actual]}/{actual}.lua'
